const dummyFaculties: IFaculty[] = [
	{
		name: "Rakesh",
		email: "johndoe@example.com",
		department: "Computer Science",
		role: "Professor",
		_id: "1",
	},
	{
		name: "Jane Smith",
		email: "janesmith@example.com",
		department: "Mathematics",
		role: "Associate Professor",
		_id: "2",
	},
	{
		name: "Mike Johnson",
		email: "mikejohnson@example.com",
		department: "Physics",
		role: "Assistant Professor",
		_id: "3",
	},
	{
		name: "Sara Wilson",
		email: "sarawilson@example.com",
		department: "Chemistry",
		role: "Lecturer",
		_id: "4",
	},
	{
		name: "David Brown",
		email: "davidbrown@example.com",
		department: "Biology",
		role: "Lecturer",
		_id: "5",
	},
	{
		name: "Amy Thompson",
		email: "amythompson@example.com",
		department: "English",
		role: "Professor",
		_id: "6",
	},
	{
		name: "Mark Davis",
		email: "markdavis@example.com",
		department: "History",
		role: "Associate Professor",
		_id: "7",
	},
	{
		name: "Emily Clark",
		email: "emilyclark@example.com",
		department: "Art",
		role: "Assistant Professor",
		_id: "8",
	},
	{
		name: "Robert Lee",
		email: "robertlee@example.com",
		department: "Music",
		role: "Lecturer",
		_id: "9",
	},
	{
		name: "Julia Garcia",
		email: "juliagarcia@example.com",
		department: "Psychology",
		role: "Lecturer",
		_id: "10",
	},
	{
		name: "John Doe",
		email: "johndoe@example.com",
		department: "Computer Science",
		role: "Professor",
		_id: "1",
	},
	{
		name: "Jane Smith",
		email: "janesmith@example.com",
		department: "Mathematics",
		role: "Associate Professor",
		_id: "2",
	},
	{
		name: "Mike Johnson",
		email: "mikejohnson@example.com",
		department: "Physics",
		role: "Assistant Professor",
		_id: "3",
	},
	{
		name: "Sara Wilson",
		email: "sarawilson@example.com",
		department: "Chemistry",
		role: "Lecturer",
		_id: "4",
	},
	{
		name: "David Brown",
		email: "davidbrown@example.com",
		department: "Biology",
		role: "Lecturer",
		_id: "5",
	},
	{
		name: "Amy Thompson",
		email: "amythompson@example.com",
		department: "English",
		role: "Professor",
		_id: "6",
	},
	{
		name: "Mark Davis",
		email: "markdavis@example.com",
		department: "History",
		role: "Associate Professor",
		_id: "7",
	},
	{
		name: "Emily Clark",
		email: "emilyclark@example.com",
		department: "Art",
		role: "Assistant Professor",
		_id: "8",
	},
	{
		name: "Robert Lee",
		email: "robertlee@example.com",
		department: "Music",
		role: "Lecturer",
		_id: "9",
	},
	{
		name: "Julia Garcia",
		email: "juliagarcia@example.com",
		department: "Psychology",
		role: "Lecturer",
		_id: "10",
	},
];

export default dummyFaculties;
